In [1]:
import polars as pl 
import polars_ds as pds 
import requests 
import json 
from utils import scrape_ticket_sections, get_available_events, scrape_match_results

In [2]:
available_events = get_available_events()

In [ ]:
for event in available_events:
    print(event['event_id'])

1085523
1187151
1188514

In [5]:
season_2026 = scrape_match_results(season_id=2025,year = 2026)

In [ ]:
pl.DataFrame(season_2026).filter(pl.col/())

shape: (25, 5)
┌────────────┬─────────────────┬──────────────┬─────────────┬─────────────────────────────────┐
│ date       ┆ home_team       ┆ away_team    ┆ result      ┆ brann_goal_scorers              │
│ ---        ┆ ---             ┆ ---          ┆ ---         ┆ ---                             │
│ date       ┆ str             ┆ str          ┆ str         ┆ list[str]                       │
╞════════════╪═════════════════╪══════════════╪═════════════╪═════════════════════════════════╡
│ 2026-03-15 ┆ Kristiansund BK ┆ SK Brann     ┆ 3:2         ┆ ["J. Soltvedt", "B. Finne"]     │
│ 2026-03-22 ┆ SK Brann        ┆ Tromsø IL    ┆ 1:2         ┆ ["F. Myhre"]                    │
│ 2026-04-06 ┆ HamKam          ┆ SK Brann     ┆ 1:5         ┆ ["N. Holm", "J. Thorsteinsson"… │
│ 2026-04-12 ┆ SK Brann        ┆ Sandefjord   ┆ 0:1         ┆ []                              │
│ 2026-04-18 ┆ Viking FK       ┆ SK Brann     ┆ 3:2         ┆ ["N. Holm", "J. Soltvedt"]      │
│ …          ┆ …               ┆ …            ┆ …           ┆ …                               │
│ 2026-02-26 ┆ Bologna         ┆ SK Brann     ┆ 1:0         ┆ []                              │
│ 2026-03-08 ┆ Tromsdalen      ┆ SK Brann     ┆ 2:3 AET     ┆ ["F. Myhre", "J. Thorsteinsson… │
│ 2026-03-19 ┆ Bryne           ┆ SK Brann     ┆ 1:2         ┆ ["J. Lungi Sørensen", "N. Holm… │
│ 2026-04-22 ┆ SK Brann        ┆ Aalesunds FK ┆ 2:1         ┆ ["U. Mathisen"]                 │
│ 2026-05-09 ┆ Bodø/Glimt      ┆ SK Brann     ┆ 7:5 on pens ┆ ["F. Myhre", "K. Ingason", "J.… │
└────────────┴─────────────────┴──────────────┴─────────────┴─────────────────────────────────┘

In [4]:
paok = scrape_ticket_sections(1187151)

In [18]:
pl.DataFrame(paok).filter(pl.col('total_seats')==0,pl.col('sold')==0)

shape: (8, 10)
┌─────────────┬──────────┬────────────┬────────────┬───┬───────────┬────────────┬──────────┬───────┐
│ snapshot_at ┆ event_id ┆ section_id ┆ section_na ┆ … ┆ available ┆ unavailabl ┆ sold_out ┆ other │
│ ---         ┆ ---      ┆ ---        ┆ me         ┆   ┆ ---       ┆ e          ┆ ---      ┆ ---   │
│ datetime[μs ┆ i64      ┆ i64        ┆ ---        ┆   ┆ i64       ┆ ---        ┆ bool     ┆ i64   │
│ , UTC]      ┆          ┆            ┆ str        ┆   ┆           ┆ i64        ┆          ┆       │
╞═════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪════════════╪══════════╪═══════╡
│ 2026-08-22  ┆ 1187151  ┆ 755042     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ -          ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ STÅPLASSER ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755020     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt A     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755046     ┆ EGD        ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Hjørnet    ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755026     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ NEDRE      ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755021     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt C     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755043     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt B     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755038     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755041     ┆ Gangen     ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Frydenbø   ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
└─────────────┴──────────┴────────────┴────────────┴───┴───────────┴────────────┴──────────┴───────┘