In [12]:
import polars as pl 
import polars_ds as pds 
import requests 
import json 
from utils import scrape_ticket_sections, get_available_events, scrape_match_results, scrape_eliteserien_results,create_table_after_round

In [2]:
available_events = get_available_events()

In [3]:
for event in available_events:
    print(event['event_id'])

1085523
1187151
1188514

In [2]:
eliteserien_results = scrape_eliteserien_results(season_id = 2025,year = 2026)

In [3]:
create_table_after_round(eliteserien_results)

shape: (272, 11)
┌──────────┬────────────┬────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ matchday ┆ team       ┆ points ┆ goals_for ┆ … ┆ total_goal ┆ total_goal ┆ total_goa ┆ table_pos │
│ ---      ┆ ---        ┆ ---    ┆ ---       ┆   ┆ s_for      ┆ s_against  ┆ l_differe ┆ ition     │
│ i64      ┆ str        ┆ i32    ┆ i64       ┆   ┆ ---        ┆ ---        ┆ nce       ┆ ---       │
│          ┆            ┆        ┆           ┆   ┆ i64        ┆ i64        ┆ ---       ┆ u32       │
│          ┆            ┆        ┆           ┆   ┆            ┆            ┆ i64       ┆           │
╞══════════╪════════════╪════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1        ┆ HamKam     ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 1          ┆ 1         ┆ 1         │
│ 1        ┆ KFUM Oslo  ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ 1        ┆ Kristiansu ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 2          ┆ 1         ┆ 1         │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Lillestrøm ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 1          ┆ 2         ┆ 1         │
│          ┆ SK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Molde FK   ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ …        ┆ …          ┆ …      ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 18       ┆ KFUM Oslo  ┆ 1      ┆ 1         ┆ … ┆ 19         ┆ 27         ┆ -8        ┆ 12        │
│ 18       ┆ Sandefjord ┆ 3      ┆ 2         ┆ … ┆ 15         ┆ 23         ┆ -8        ┆ 13        │
│ 18       ┆ Aalesunds  ┆ 1      ┆ 5         ┆ … ┆ 27         ┆ 41         ┆ -14       ┆ 14        │
│          ┆ FK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ Kristiansu ┆ 0      ┆ 0         ┆ … ┆ 15         ┆ 27         ┆ -12       ┆ 14        │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ IK Start   ┆ 0      ┆ 0         ┆ … ┆ 16         ┆ 38         ┆ -22       ┆ 16        │
└──────────┴────────────┴────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [ ]:
import polars as pl

matches = pl.DataFrame(eliteserien_results)

# Hent målene fra resultatet
matches = matches.with_columns([
    pl.col("result")
      .str.split_exact(":", 1)
      .struct.field("field_0")
      .cast(pl.Int64)
      .alias("home_goals"),

    pl.col("result")
      .str.split_exact(":", 1)
      .struct.field("field_1")
      .cast(pl.Int64)
      .alias("away_goals"),
])

# Lag en rad for hjemmelaget
home = matches.select([
    "matchday",
    pl.col("home_team").alias("team"),
    pl.col("home_goals").alias("goals_for"),
    pl.col("away_goals").alias("goals_against"),
    pl.when(pl.col("home_goals") > pl.col("away_goals"))
      .then(3)
      .when(pl.col("home_goals") == pl.col("away_goals"))
      .then(1)
      .otherwise(0)
      .alias("points"),
])

# Lag en rad for bortelaget
away = matches.select([
    "matchday",
    pl.col("away_team").alias("team"),
    pl.col("away_goals").alias("goals_for"),
    pl.col("home_goals").alias("goals_against"),
    pl.when(pl.col("away_goals") > pl.col("home_goals"))
      .then(3)
      .when(pl.col("away_goals") == pl.col("home_goals"))
      .then(1)
      .otherwise(0)
      .alias("points"),
])

# Slå sammen hjemmelag og bortelag
team_results = pl.concat([home, away])

# Summer resultatene per lag per runde
round_table = (
    team_results
    .group_by(["matchday", "team"])
    .agg([
        pl.col("points").sum(),
        pl.col("goals_for").sum(),
        pl.col("goals_against").sum(),
    ])
    .with_columns(
        (pl.col("goals_for") - pl.col("goals_against"))
        .alias("goal_difference")
    )
    .sort(["team", "matchday"])
)

# Beregn totalsummen etter hver runde
table_after_round = round_table.with_columns([
    pl.col("points")
      .cum_sum()
      .over("team")
      .alias("total_points"),

    pl.col("goals_for")
      .cum_sum()
      .over("team")
      .alias("total_goals_for"),

    pl.col("goals_against")
      .cum_sum()
      .over("team")
      .alias("total_goals_against"),

    pl.col("goal_difference")
      .cum_sum()
      .over("team")
      .alias("total_goal_difference"),
])

# Beregn tabellplassering etter hver runde
table_after_round = (
    table_after_round
    .with_columns(
        pl.col("total_points")
          .rank("min", descending=True)
          .over("matchday")
          .alias("table_position")
    )
    .sort(["matchday", "table_position", "team"])
)

shape: (17, 11)
┌──────────┬──────────┬────────┬───────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ matchday ┆ team     ┆ points ┆ goals_for ┆ … ┆ total_goal ┆ total_goal ┆ total_goal ┆ table_posi │
│ ---      ┆ ---      ┆ ---    ┆ ---       ┆   ┆ s_for      ┆ s_against  ┆ _differenc ┆ tion       │
│ i64      ┆ str      ┆ i32    ┆ i64       ┆   ┆ ---        ┆ ---        ┆ e          ┆ ---        │
│          ┆          ┆        ┆           ┆   ┆ i64        ┆ i64        ┆ ---        ┆ u32        │
│          ┆          ┆        ┆           ┆   ┆            ┆            ┆ i64        ┆            │
╞══════════╪══════════╪════════╪═══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1        ┆ SK Brann ┆ 0      ┆ 2         ┆ … ┆ 2          ┆ 3          ┆ -1         ┆ 10         │
│ 2        ┆ SK Brann ┆ 0      ┆ 1         ┆ … ┆ 3          ┆ 5          ┆ -2         ┆ 14         │
│ 3        ┆ SK Brann ┆ 3      ┆ 5         ┆ … ┆ 8          ┆ 6          ┆ 2          ┆ 9          │
│ 4        ┆ SK Brann ┆ 0      ┆ 0         ┆ … ┆ 8          ┆ 7          ┆ 1          ┆ 12         │
│ 5        ┆ SK Brann ┆ 0      ┆ 2         ┆ … ┆ 10         ┆ 10         ┆ 0          ┆ 14         │
│ …        ┆ …        ┆ …      ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 14       ┆ SK Brann ┆ 3      ┆ 2         ┆ … ┆ 23         ┆ 22         ┆ 1          ┆ 9          │
│ 15       ┆ SK Brann ┆ 0      ┆ 2         ┆ … ┆ 25         ┆ 25         ┆ 0          ┆ 10         │
│ 16       ┆ SK Brann ┆ 3      ┆ 3         ┆ … ┆ 28         ┆ 27         ┆ 1          ┆ 9          │
│ 17       ┆ SK Brann ┆ 3      ┆ 5         ┆ … ┆ 33         ┆ 27         ┆ 6          ┆ 6          │
│ 18       ┆ SK Brann ┆ 3      ┆ 3         ┆ … ┆ 36         ┆ 27         ┆ 9          ┆ 6          │
└──────────┴──────────┴────────┴───────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [2]:
season_2026 = scrape_match_results(season_id=2025,year = 2026)

In [4]:
pl.DataFrame(season_2026).sort(by = 'date')

shape: (25, 7)
┌────────────┬────────────┬──────────────┬─────────┬───────────────┬───────────────┬───────────────┐
│ date       ┆ home_team  ┆ away_team    ┆ result  ┆ brann_table_p ┆ snapshot_at   ┆ brann_goal_sc │
│ ---        ┆ ---        ┆ ---          ┆ ---     ┆ osition       ┆ ---           ┆ orers         │
│ date       ┆ str        ┆ str          ┆ str     ┆ ---           ┆ datetime[μs,  ┆ ---           │
│            ┆            ┆              ┆         ┆ i64           ┆ UTC]          ┆ list[str]     │
╞════════════╪════════════╪══════════════╪═════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2026-01-22 ┆ SK Brann   ┆ Midtjylland  ┆ 3:3     ┆ null          ┆ 2026-08-23    ┆ ["N. Holm",   │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "E. Kornvig", │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "J. …         │
│ 2026-01-29 ┆ Sturm Graz ┆ SK Brann     ┆ 1:0     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-02-19 ┆ SK Brann   ┆ Bologna      ┆ 0:1     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-02-26 ┆ Bologna    ┆ SK Brann     ┆ 1:0     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-03-08 ┆ Tromsdalen ┆ SK Brann     ┆ 2:3 AET ┆ null          ┆ 2026-08-23    ┆ ["F. Myhre",  │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "J. Thorstein │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ sson…         │
│ …          ┆ …          ┆ …            ┆ …       ┆ …             ┆ …             ┆ …             │
│ 2026-07-12 ┆ SK Brann   ┆ IK Start     ┆ 2:1     ┆ null          ┆ 2026-08-23    ┆ ["N. Holm",   │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "K. Eriksen"] │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-07-18 ┆ Molde FK   ┆ SK Brann     ┆ 1:2     ┆ null          ┆ 2026-08-23    ┆ ["D. De       │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ Roeve", "K.   │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ Eriksen"]     │
│ 2026-07-26 ┆ SK Brann   ┆ Vålerenga    ┆ 2:3     ┆ null          ┆ 2026-08-23    ┆ ["N. Castro", │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "F. Myhre"]   │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-08-02 ┆ SK Brann   ┆ Rosenborg BK ┆ 3:2     ┆ null          ┆ 2026-08-23    ┆ ["N. Castro", │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "K. Ingason", │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "K…           │
│ 2026-08-16 ┆ SK Brann   ┆ HamKam       ┆ 3:0     ┆ null          ┆ 2026-08-23    ┆ ["J.          │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ Soltvedt",    │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "N. Holm",    │
│            ┆            ┆              ┆         ┆               ┆               ┆ "B.…          │
└────────────┴────────────┴──────────────┴─────────┴───────────────┴───────────────┴───────────────┘

In [4]:
paok = scrape_ticket_sections(1187151)

In [18]:
pl.DataFrame(paok).filter(pl.col('total_seats')==0,pl.col('sold')==0)

shape: (8, 10)
┌─────────────┬──────────┬────────────┬────────────┬───┬───────────┬────────────┬──────────┬───────┐
│ snapshot_at ┆ event_id ┆ section_id ┆ section_na ┆ … ┆ available ┆ unavailabl ┆ sold_out ┆ other │
│ ---         ┆ ---      ┆ ---        ┆ me         ┆   ┆ ---       ┆ e          ┆ ---      ┆ ---   │
│ datetime[μs ┆ i64      ┆ i64        ┆ ---        ┆   ┆ i64       ┆ ---        ┆ bool     ┆ i64   │
│ , UTC]      ┆          ┆            ┆ str        ┆   ┆           ┆ i64        ┆          ┆       │
╞═════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪════════════╪══════════╪═══════╡
│ 2026-08-22  ┆ 1187151  ┆ 755042     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ -          ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ STÅPLASSER ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755020     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt A     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755046     ┆ EGD        ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Hjørnet    ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755026     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ NEDRE      ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755021     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt C     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755043     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt B     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755038     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755041     ┆ Gangen     ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Frydenbø   ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
└─────────────┴──────────┴────────────┴────────────┴───┴───────────┴────────────┴──────────┴───────┘