In [6]:
import polars as pl 
import duckdb 
import polars_ds as pds 
import requests 
import json 
from utils import scrape_ticket_sections, get_available_events, scrape_match_results, scrape_eliteserien_results,create_table_after_round

In [11]:
from pathlib import Path

database_path = Path.cwd() / "ticket_sales.duckdb"

with duckdb.connect(str(database_path), read_only=True) as connection:
    snapshots = connection.sql("""
        SELECT
            CAST(snapshot_at AS VARCHAR) AS snapshot_at,
            event_id,
            section_id,
            section_name,
            total_seats,
            sold,
            available,
            unavailable,
            sold_out,
            other
        FROM ticket_snapshots
        ORDER BY snapshot_at, section_name
    """).pl()

snapshots

C:\Users\Yafee Ishraq\AppData\Local\Temp\ipykernel_16276\3277816103.py:20: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  """).pl()

shape: (144, 10)
┌─────────────┬──────────┬────────────┬────────────┬───┬───────────┬────────────┬──────────┬───────┐
│ snapshot_at ┆ event_id ┆ section_id ┆ section_na ┆ … ┆ available ┆ unavailabl ┆ sold_out ┆ other │
│ ---         ┆ ---      ┆ ---        ┆ me         ┆   ┆ ---       ┆ e          ┆ ---      ┆ ---   │
│ str         ┆ i32      ┆ i32        ┆ ---        ┆   ┆ i32       ┆ ---        ┆ bool     ┆ i32   │
│             ┆          ┆            ┆ str        ┆   ┆           ┆ i32        ┆          ┆       │
╞═════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪════════════╪══════════╪═══════╡
│ 2026-08-24  ┆ 1187151  ┆ 755045     ┆ BT -       ┆ … ┆ 11        ┆ 21         ┆ false    ┆ 11    │
│ 10:10:41.58 ┆          ┆            ┆ Rullestol  ┆   ┆           ┆            ┆          ┆       │
│ 0859+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755035     ┆ BT Felt A  ┆ … ┆ 191       ┆ 168        ┆ false    ┆ 0     │
│ 10:10:41.58 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 0859+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755023     ┆ BT Felt A  ┆ … ┆ 0         ┆ 93         ┆ true     ┆ 93    │
│ 10:10:41.58 ┆          ┆            ┆ Øvre       ┆   ┆           ┆            ┆          ┆       │
│ 0859+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755036     ┆ BT Felt B  ┆ … ┆ 0         ┆ 574        ┆ true     ┆ 18    │
│ 10:10:41.58 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 0859+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755055     ┆ BT Felt C  ┆ … ┆ 0         ┆ 732        ┆ true     ┆ 0     │
│ 10:10:41.58 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 0859+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ …           ┆ …        ┆ …          ┆ …          ┆ … ┆ …         ┆ …          ┆ …        ┆ …     │
│ 2026-08-24  ┆ 1187151  ┆ 755052     ┆ VIP 1      ┆ … ┆ 113       ┆ 34         ┆ false    ┆ 0     │
│ 10:11:59.45 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 6004+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755063     ┆ VIP 2      ┆ … ┆ 46        ┆ 110        ┆ false    ┆ 0     │
│ 10:11:59.45 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 6004+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755064     ┆ VIP 3      ┆ … ┆ 63        ┆ 93         ┆ false    ┆ 4     │
│ 10:11:59.45 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 6004+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755050     ┆ VIP 4      ┆ … ┆ 50        ┆ 75         ┆ false    ┆ 0     │
│ 10:11:59.45 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 6004+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-24  ┆ 1187151  ┆ 755059     ┆ VIP 5      ┆ … ┆ 107       ┆ 28         ┆ false    ┆ 0     │
│ 10:11:59.45 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 6004+02     ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
└─────────────┴──────────┴────────────┴────────────┴───┴───────────┴────────────┴──────────┴───────┘

In [2]:
available_events = get_available_events()

In [3]:
for event in available_events:
    print(event['event_id'])

1085523
1187151
1188514

In [35]:
eliteserien_results = scrape_eliteserien_results(season_id = 2025,year = 2026)

In [36]:
create_table_after_round(eliteserien_results)

shape: (272, 11)
┌──────────┬────────────┬────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ matchday ┆ team       ┆ points ┆ goals_for ┆ … ┆ total_goal ┆ total_goal ┆ total_goa ┆ table_pos │
│ ---      ┆ ---        ┆ ---    ┆ ---       ┆   ┆ s_for      ┆ s_against  ┆ l_differe ┆ ition     │
│ i64      ┆ str        ┆ i32    ┆ i64       ┆   ┆ ---        ┆ ---        ┆ nce       ┆ ---       │
│          ┆            ┆        ┆           ┆   ┆ i64        ┆ i64        ┆ ---       ┆ u32       │
│          ┆            ┆        ┆           ┆   ┆            ┆            ┆ i64       ┆           │
╞══════════╪════════════╪════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1        ┆ HamKam     ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 1          ┆ 1         ┆ 1         │
│ 1        ┆ KFUM Oslo  ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ 1        ┆ Kristiansu ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 2          ┆ 1         ┆ 1         │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Lillestrøm ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 1          ┆ 2         ┆ 1         │
│          ┆ SK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Molde FK   ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ …        ┆ …          ┆ …      ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 18       ┆ KFUM Oslo  ┆ 1      ┆ 1         ┆ … ┆ 19         ┆ 27         ┆ -8        ┆ 12        │
│ 18       ┆ Sandefjord ┆ 3      ┆ 2         ┆ … ┆ 15         ┆ 23         ┆ -8        ┆ 13        │
│ 18       ┆ Aalesunds  ┆ 1      ┆ 5         ┆ … ┆ 27         ┆ 41         ┆ -14       ┆ 14        │
│          ┆ FK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ Kristiansu ┆ 0      ┆ 0         ┆ … ┆ 15         ┆ 27         ┆ -12       ┆ 14        │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ IK Start   ┆ 0      ┆ 0         ┆ … ┆ 16         ┆ 38         ┆ -22       ┆ 16        │
└──────────┴────────────┴────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [2]:
season_2026 = scrape_match_results(season_id=2025,year = 2026)

In [4]:
pl.DataFrame(season_2026).sort(by = 'date')

shape: (25, 7)
┌────────────┬────────────┬──────────────┬─────────┬───────────────┬───────────────┬───────────────┐
│ date       ┆ home_team  ┆ away_team    ┆ result  ┆ brann_table_p ┆ snapshot_at   ┆ brann_goal_sc │
│ ---        ┆ ---        ┆ ---          ┆ ---     ┆ osition       ┆ ---           ┆ orers         │
│ date       ┆ str        ┆ str          ┆ str     ┆ ---           ┆ datetime[μs,  ┆ ---           │
│            ┆            ┆              ┆         ┆ i64           ┆ UTC]          ┆ list[str]     │
╞════════════╪════════════╪══════════════╪═════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2026-01-22 ┆ SK Brann   ┆ Midtjylland  ┆ 3:3     ┆ null          ┆ 2026-08-23    ┆ ["N. Holm",   │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "E. Kornvig", │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "J. …         │
│ 2026-01-29 ┆ Sturm Graz ┆ SK Brann     ┆ 1:0     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-02-19 ┆ SK Brann   ┆ Bologna      ┆ 0:1     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-02-26 ┆ Bologna    ┆ SK Brann     ┆ 1:0     ┆ null          ┆ 2026-08-23    ┆ []            │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆               │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-03-08 ┆ Tromsdalen ┆ SK Brann     ┆ 2:3 AET ┆ null          ┆ 2026-08-23    ┆ ["F. Myhre",  │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "J. Thorstein │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ sson…         │
│ …          ┆ …          ┆ …            ┆ …       ┆ …             ┆ …             ┆ …             │
│ 2026-07-12 ┆ SK Brann   ┆ IK Start     ┆ 2:1     ┆ null          ┆ 2026-08-23    ┆ ["N. Holm",   │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "K. Eriksen"] │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-07-18 ┆ Molde FK   ┆ SK Brann     ┆ 1:2     ┆ null          ┆ 2026-08-23    ┆ ["D. De       │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ Roeve", "K.   │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ Eriksen"]     │
│ 2026-07-26 ┆ SK Brann   ┆ Vålerenga    ┆ 2:3     ┆ null          ┆ 2026-08-23    ┆ ["N. Castro", │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "F. Myhre"]   │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆               │
│ 2026-08-02 ┆ SK Brann   ┆ Rosenborg BK ┆ 3:2     ┆ null          ┆ 2026-08-23    ┆ ["N. Castro", │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ "K. Ingason", │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "K…           │
│ 2026-08-16 ┆ SK Brann   ┆ HamKam       ┆ 3:0     ┆ null          ┆ 2026-08-23    ┆ ["J.          │
│            ┆            ┆              ┆         ┆               ┆ 08:53:52.5397 ┆ Soltvedt",    │
│            ┆            ┆              ┆         ┆               ┆ 82 UTC        ┆ "N. Holm",    │
│            ┆            ┆              ┆         ┆               ┆               ┆ "B.…          │
└────────────┴────────────┴──────────────┴─────────┴───────────────┴───────────────┴───────────────┘

In [4]:
paok = scrape_ticket_sections(1187151)

In [18]:
pl.DataFrame(paok).filter(pl.col('total_seats')==0,pl.col('sold')==0)

shape: (8, 10)
┌─────────────┬──────────┬────────────┬────────────┬───┬───────────┬────────────┬──────────┬───────┐
│ snapshot_at ┆ event_id ┆ section_id ┆ section_na ┆ … ┆ available ┆ unavailabl ┆ sold_out ┆ other │
│ ---         ┆ ---      ┆ ---        ┆ me         ┆   ┆ ---       ┆ e          ┆ ---      ┆ ---   │
│ datetime[μs ┆ i64      ┆ i64        ┆ ---        ┆   ┆ i64       ┆ ---        ┆ bool     ┆ i64   │
│ , UTC]      ┆          ┆            ┆ str        ┆   ┆           ┆ i64        ┆          ┆       │
╞═════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪════════════╪══════════╪═══════╡
│ 2026-08-22  ┆ 1187151  ┆ 755042     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ -          ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ STÅPLASSER ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755020     ┆ FJORDKRAFT ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt A     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755046     ┆ EGD        ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Hjørnet    ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755026     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ NEDRE      ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755021     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt C     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755043     ┆ FRYDENBØ   ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Felt B     ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆ Nedre      ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755038     ┆ STORE STÅ  ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
│ 2026-08-22  ┆ 1187151  ┆ 755041     ┆ Gangen     ┆ … ┆ 0         ┆ 0          ┆ false    ┆ 0     │
│ 20:20:11.44 ┆          ┆            ┆ Frydenbø   ┆   ┆           ┆            ┆          ┆       │
│ 9792 UTC    ┆          ┆            ┆            ┆   ┆           ┆            ┆          ┆       │
└─────────────┴──────────┴────────────┴────────────┴───┴───────────┴────────────┴──────────┴───────┘