In [6]:
import importlib
import polars as pl
import polars.selectors as cs
from datetime import datetime
import polars_ds as pds
import requests
import json
import duckdb
from pathlib import Path
from time import sleep
import src.utils as utils

importlib.reload(utils)

from src.utils import (
    scrape_eliteserien_results_for_seasons,
    scrape_transfermarkt_goal_contributions,
    scrape_eliteserien_goal_contributions_for_season,
    scrape_eliteserien_lineups_for_season,
    scrape_transfermarkt_lineups,
    scrape_fotmob_eliteserien_results_for_seasons,
    scrape_fotmob_match_report
)

import importlib
import src.agent
importlib.reload(src.agent)

In [7]:
db_path = Path("data/brann.duckdb")

In [27]:
src.agent.run_question("Hvor mange assis har Zlatko Tripic hatt hittil i sesongen 2026?")

15

In [34]:
for event in src.agent.agent.stream(
    {"question": "Hvor mange assists har Zlatko Tripic hatt hittil i sesongen 2026?"
    ""},
    stream_mode="updates",
):
    print(event)

{'plan_tasks': {'tasks': ['Finn totalt antall assists Zlatko Tripic har hatt i sesongen 2026.'], 'task_index': 0, 'generated_sqls': [], 'collected_results': [], 'current_task': 'Finn totalt antall assists Zlatko Tripic har hatt i sesongen 2026.', 'sql_error': '', 'attempts': 0}}
{'generate_sql': {'current_task': 'Finn totalt antall assists Zlatko Tripic har hatt i sesongen 2026.', 'sql': "SELECT COUNT(*) AS total_assists\nFROM fct_goal_contributions\nWHERE season = 2026\n  AND assist_name = 'Zlatko Tripic'", 'attempts': 1}}
{'execute_sql': {'columns': ['total_assists'], 'rows': [(15,)], 'sql_error': ''}}
{'collect_result': {'collected_results': [{'task': 'Finn totalt antall assists Zlatko Tripic har hatt i sesongen 2026.', 'sql': "SELECT COUNT(*) AS total_assists\nFROM fct_goal_contributions\nWHERE season = 2026\n  AND assist_name = 'Zlatko Tripic'", 'columns': ['total_assists'], 'rows': [(15,)], 'truncated': False}], 'generated_sqls': ["SELECT COUNT(*) AS total_assists\nFROM fct_goal_contributions\nWHERE season = 2026\n  AND assist_name = 'Zlatko Tripic'"], 'task_index': 1, 'current_task': '', 'sql_error': '', 'attempts': 0}}
{'summarize_results': {'summary': '15'}}

In [14]:
con = duckdb.connect(str(Path(db_path)))

query = """
WITH brann_goals AS (
    SELECT
        assist_name,
        COUNT(*) AS assists
    FROM fct_goal_contributions
    WHERE season = 2026
      AND scorer_team = 'Brann'
      AND is_own_goal = false
    GROUP BY assist_name
)
SELECT
    assist_name,
    assists
FROM brann_goals
order by assists desc
"""

result = con.execute(query).arrow()
pl.from_arrow(result)

shape: (13, 2)
┌────────────────────────┬─────────┐
│ assist_name            ┆ assists │
│ ---                    ┆ ---     │
│ str                    ┆ i64     │
╞════════════════════════╪═════════╡
│ null                   ┆ 11      │
│ Ulrik Mathisen         ┆ 5       │
│ Kristian Eriksen       ┆ 4       │
│ Noah Holm              ┆ 3       │
│ Niklas Castro          ┆ 3       │
│ …                      ┆ …       │
│ Denzel De Roeve        ┆ 2       │
│ Niklas Jensen Wassberg ┆ 1       │
│ Jón Thorsteinsson      ┆ 1       │
│ Felix Horn Myhre       ┆ 1       │
│ Jacob Lungi Sørensen   ┆ 1       │
└────────────────────────┴─────────┘

In [26]:
con.close()

In [61]:
con = duckdb.connect(str(Path(db_path)))

query = """
    SELECT *
FROM fct_goal_contributions 
where assist_player_id = 536981

"""

result = con.execute(query).arrow()
(
pl.from_arrow(result)
#.unnest('event_title')
#.filter(pl.col('value').str.contains('Assist'))
#.filter(pl.col('assist_name').str.contains('Zlatko'))

)

shape: (10, 17)
┌────────┬────────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ season ┆ date       ┆ matchday ┆ home_team  ┆ … ┆ is_own_goa ┆ report_ur ┆ snapshot_ ┆ ingested_ │
│ ---    ┆ ---        ┆ ---      ┆ ---        ┆   ┆ l          ┆ l         ┆ at        ┆ at        │
│ i64    ┆ date       ┆ i64      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│        ┆            ┆          ┆            ┆   ┆ bool       ┆ str       ┆ datetime[ ┆ datetime[ │
│        ┆            ┆          ┆            ┆   ┆            ┆           ┆ μs, Europ ┆ μs]       │
│        ┆            ┆          ┆            ┆   ┆            ┆           ┆ e/Oslo]   ┆           │
╞════════╪════════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2021   ┆ 2021-06-19 ┆ 8        ┆ Sandefjord ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-07-28 ┆ 2        ┆ Odds       ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ Ballklubb  ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-10-24 ┆ 23       ┆ Rosenborg  ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2024   ┆ 2024-05-16 ┆ 8        ┆ Sarpsborg  ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ 08         ┆   ┆            ┆ ww.fotmob ┆ 8 13:24:2 ┆ 8 13:25:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 3.363340  ┆ 9.012184  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2024   ┆ 2024-09-21 ┆ 23       ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:24:2 ┆ 8 13:25:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 3.363340  ┆ 9.012184  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2025   ┆ 2025-10-26 ┆ 26       ┆ Kristiansu ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ nd         ┆   ┆            ┆ ww.fotmob ┆ 8 13:25:2 ┆ 8 13:26:2 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 9.818154  ┆ 2.630084  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2025   ┆ 2025-11-02 ┆ 27       ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:25:2 ┆ 8 13:26:2 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 9.818154  ┆ 2.630084  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2025   ┆ 2025-11-02 ┆ 27       ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:25:2 ┆ 8 13:26:2 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 9.818154  ┆ 2.630084  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-04-12 ┆ 4        ┆ Molde      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-04-19 ┆ 5        ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
└────────┴────────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
from openai import OpenAI

client = OpenAI()

for model in client.models.list().data:
    print(model.id)

gpt-4-0613
gpt-4
gpt-3.5-turbo
gpt-6-astra
gpt-realtime-2.1
gpt-realtime-2.1-mini
gpt-transcribe
gpt-live-transcribe
davinci-002
babbage-002
gpt-3.5-turbo-instruct
gpt-3.5-turbo-instruct-0914
gpt-3.5-turbo-1106
tts-1-hd
tts-1-1106
tts-1-hd-1106
text-embedding-3-small
text-embedding-3-large
gpt-3.5-turbo-0125
gpt-4-turbo
gpt-4-turbo-2024-04-09
gpt-4o
gpt-4o-2024-05-13
gpt-4o-mini-2024-07-18
gpt-4o-mini
gpt-4o-2024-08-06
omni-moderation-latest
omni-moderation-2024-09-26
o1-2024-12-17
o1
o3-mini
o3-mini-2025-01-31
gpt-4o-2024-11-20
gpt-4o-mini-search-preview-2025-03-11
gpt-4o-mini-search-preview
gpt-4o-transcribe
gpt-4o-mini-transcribe
o1-pro-2025-03-19
o1-pro
gpt-4o-mini-tts
o3-2025-04-16
o4-mini-2025-04-16
o3
o4-mini
gpt-4.1-2025-04-14
gpt-4.1
gpt-4.1-mini-2025-04-14
gpt-4.1-mini
gpt-4.1-nano-2025-04-14
gpt-4.1-nano
gpt-image-1
gpt-4o-transcribe-diarize
gpt-5-chat-latest
gpt-5-2025-08-07
gpt-5
gpt-5-mini-2025-08-07
gpt-5-mini
gpt-5-nano-2025-08-07
gpt-5-nano
gpt-audio-2025-08-28
gpt-realtime
gpt-realtime-2025-08-28
gpt-audio
gpt-5-codex
gpt-image-1-mini
gpt-5-pro-2025-10-06
gpt-5-pro
gpt-audio-mini
gpt-audio-mini-2025-10-06
gpt-5-search-api
gpt-realtime-mini
sora-2
sora-2-pro
gpt-5-search-api-2025-10-14
gpt-5.1-chat-latest
gpt-5.1-2025-11-13
gpt-5.1
gpt-5.1-codex
gpt-5.1-codex-mini
gpt-5.1-codex-max
gpt-image-1.5
gpt-5.2-2025-12-11
gpt-5.2
gpt-5.2-pro-2025-12-11
gpt-5.2-pro
gpt-5.2-chat-latest
gpt-4o-mini-transcribe-2025-12-15
gpt-4o-mini-transcribe-2025-03-20
gpt-4o-mini-tts-2025-03-20
gpt-4o-mini-tts-2025-12-15
gpt-realtime-mini-2025-12-15
gpt-audio-mini-2025-12-15
chatgpt-image-latest
gpt-5.2-codex
gpt-5.3-codex
gpt-realtime-1.5
gpt-audio-1.5
gpt-4o-search-preview
gpt-4o-search-preview-2025-03-11
gpt-5.3-chat-latest
gpt-5.4-2026-03-05
gpt-5.4-pro
gpt-5.4-pro-2026-03-05
gpt-5.4
gpt-5.4-nano-2026-03-17
gpt-5.4-nano
gpt-5.4-mini-2026-03-17
gpt-5.4-mini
gpt-image-2
gpt-image-2-2026-04-21
gpt-5.5
gpt-5.5-2026-04-23
gpt-5.5-pro
gpt-5.5-pro-2026-04-23
chat-latest
gpt-realtime-translate
gpt-realtime-2
gpt-realtime-whisper
gpt-5.6-sol
gpt-5.6-terra
gpt-5.6-luna
gpt-3.5-turbo-16k
tts-1
whisper-1
text-embedding-ada-002

In [ ]:
client.models.list().data

[Model(id='gpt-4-0613', created=1686588896, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-4', created=1687882411, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-3.5-turbo', created=1677610602, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-6-astra', created=1787853604, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2.1', created=1782254687, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2.1-mini', created=1782254706, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-transcribe', created=1785168027, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-live-transcribe', created=1785168034, object='model', owned_by='system', shutdown_date=None),
 Model(id='davinci-002', created=1692634301, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='babbage-002', created=1692634615, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='gpt-3.5-turbo-instruct', created=1692901427, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='gpt-3.5-turbo-instruct-0914', created=1694122472, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-1106', created=1698959748, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='tts-1-hd', created=1699046015, object='model', owned_by='system', shutdown_date=None),
 Model(id='tts-1-1106', created=1699053241, object='model', owned_by='system', shutdown_date=None),
 Model(id='tts-1-hd-1106', created=1699053533, object='model', owned_by='system', shutdown_date=None),
 Model(id='text-embedding-3-small', created=1705948997, object='model', owned_by='system', shutdown_date=None),
 Model(id='text-embedding-3-large', created=1705953180, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-0125', created=1706048358, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4-turbo', created=1712361441, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4-turbo-2024-04-09', created=1712601677, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o', created=1715367049, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-2024-05-13', created=1715368132, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-mini-2024-07-18', created=1721172717, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini', created=1721172741, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-2024-08-06', created=1722814719, object='model', owned_by='system', shutdown_date=None),
 Model(id='omni-moderation-latest', created=1731689265, object='model', owned_by='system', shutdown_date=None),
 Model(id='omni-moderation-2024-09-26', created=1732734466, object='model', owned_by='system', shutdown_date=None),
 Model(id='o1-2024-12-17', created=1734326976, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o1', created=1734375816, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3-mini', created=1737146383, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3-mini-2025-01-31', created=1738010200, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-2024-11-20', created=1739331543, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-search-preview-2025-03-11', created=1741390858, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-4o-mini-search-preview', created=1741391161, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-transcribe', created=1742068463, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-transcribe', created=1742068596, object='model', owned_by='system', shutdown_date=None),
 Model(id='o1-pro-2025-03-19', created=1742251504, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o1-pro', created=1742251791, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-mini-tts', created=1742403959, object='model', owned_by='system', shutdown_date=None),
 Model(id='o3-2025-04-16', created=1744133301, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='o4-mini-2025-04-16', created=1744133506, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3', created=1744225308, object='model', owned_by='system', shutdown_date=None),
 Model(id='o4-mini', created=1744225351, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4.1-2025-04-14', created=1744315746, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1', created=1744316542, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-mini-2025-04-14', created=1744317547, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-mini', created=1744318173, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-nano-2025-04-14', created=1744321025, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4.1-nano', created=1744321707, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-image-1', created=1745517030, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-transcribe-diarize', created=1750798887, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-chat-latest', created=1754073306, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5-2025-08-07', created=1754075360, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5', created=1754425777, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-mini-2025-08-07', created=1754425867, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-mini', created=1754425928, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-nano-2025-08-07', created=1754426303, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-nano', created=1754426384, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-2025-08-28', created=1756256146, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime', created=1756271701, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-realtime-2025-08-28', created=1756271773, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio', created=1756339249, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-5-codex', created=1757527818, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-image-1-mini', created=1758845821, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5-pro-2025-10-06', created=1759469707, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-pro', created=1759469822, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-mini', created=1759512027, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-audio-mini-2025-10-06', created=1759512137, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5-search-api', created=1759514629, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-mini', created=1759517133, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='sora-2', created=1759708615, object='model', owned_by='system', shutdown_date='2026-09-24'),
 Model(id='sora-2-pro', created=1759708663, object='model', owned_by='system', shutdown_date='2026-09-24'),
 Model(id='gpt-5-search-api-2025-10-14', created=1760043960, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1-chat-latest', created=1762547951, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-2025-11-13', created=1762800353, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1', created=1762800673, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1-codex', created=1762988221, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-codex-mini', created=1763007109, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-codex-max', created=1763671532, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-image-1.5', created=1764030620, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5.2-2025-12-11', created=1765313028, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2', created=1765313051, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-pro-2025-12-11', created=1765343959, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-pro', created=1765343983, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-chat-latest', created=1765344352, object='model', owned_by='system', shutdown_date='2026-08-10'),
 Model(id='gpt-4o-mini-transcribe-2025-12-15', created=1765610407, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-transcribe-2025-03-20', created=1765610545, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-4o-mini-tts-2025-03-20', created=1765610731, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-4o-mini-tts-2025-12-15', created=1765610837, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-mini-2025-12-15', created=1765612007, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-mini-2025-12-15', created=1765760008, object='model', owned_by='system', shutdown_date=None),
 Model(id='chatgpt-image-latest', created=1765925279, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5.2-codex', created=1766164985, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.3-codex', created=1770537915, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-1.5', created=1771461469, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-1.5', created=1771550885, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-search-preview', created=1771905534, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-search-preview-2025-03-11', created=1771905621, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.3-chat-latest', created=1772236571, object='model', owned_by='system', shutdown_date='2026-08-10'),
 Model(id='gpt-5.4-2026-03-05', created=1772654062, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-pro', created=1772659601, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-pro-2026-03-05', created=1772659657, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4', created=1772691852, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-nano-2026-03-17', created=1773450837, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-nano', created=1773450870, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-mini-2026-03-17', created=1773451076, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-mini', created=1773451123, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-image-2', created=1776399795, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-image-2-2026-04-21', created=1776399994, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5', created=1776824847, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-2026-04-23', created=1776839241, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-pro', created=1776894349, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-pro-2026-04-23', created=1776894470, object='model', owned_by='system', shutdown_date=None),
 Model(id='chat-latest', created=1777704602, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-translate', created=1777950216, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2', created=1778006032, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-whisper', created=1778012060, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-sol', created=1782228018, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-terra', created=1782228459, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-luna', created=1782228658, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-16k', created=1683758102, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='tts-1', created=1681940951, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='whisper-1', created=1677532384, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='text-embedding-ada-002', created=1671217299, object='model', owned_by='openai-internal', shutdown_date=None)]